# Generated by Django 3.1.6 on 2021-02-20 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menusName', models.CharField(max_length=20, verbose_name='菜单名字')),
                ('parentMenu', models.CharField(blank=True, default=0, help_text='添加子菜单，请选择父级菜单', max_length=20, null=True, verbose_name='父级菜单')),
                ('menusShow', models.BooleanField(default=False, help_text='菜单是否显示，默认添加不显示', verbose_name='是否显示')),
                ('menusUrl', models.CharField(blank=True, default='javascript:void(0)', help_text='设置菜单Url跳转地址', max_length=50, null=True, verbose_name='菜单Url地址')),
                ('menusPriority', models.IntegerField(blank=True, default=-1, help_text='菜单显示优先级顺序，优先级越大显示越靠前', null=True, verbose_name='菜单显示优先级')),
                ('menusPermissionId', models.IntegerField(error_messages={'field-menusPermissionId': '只能输入数字'}, help_text='给菜单设置权限Id，用于菜单权限控制', verbose_name='菜单权限Id')),
            ],
            options={
                'verbose_name': '菜单',
                'verbose_name_plural': '菜单',
                'db_table': 'adminapps_menus_info',
                'ordering': ['-menusPriority', 'id'],
            },
        ),
    ]
