# Generated by Django 3.1.6 on 2021-02-25 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapps', '0002_auto_20210225_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='menuPermissionId',
            field=models.IntegerField(error_messages={'field-menuPermissionId': '只能输入数字'}, help_text='给菜单设置权限Id，用于菜单权限控制', verbose_name='菜单权限Id'),
        ),
        migrations.AlterField(
            model_name='submenu',
            name='subMenuName',
            field=models.CharField(max_length=20, verbose_name='子菜单名字'),
        ),
        migrations.AlterField(
            model_name='submenu',
            name='subMenuPermissionId',
            field=models.IntegerField(error_messages={'field-subMenuPermissionId': '只能输入数字'}, help_text='给子菜单设置权限Id，用于菜单权限控制', verbose_name='子菜单权限Id'),
        ),
        migrations.AlterField(
            model_name='submenu',
            name='subMenuPriority',
            field=models.IntegerField(blank=True, default=-1, help_text='子菜单显示优先级顺序，优先级越大显示越靠前', null=True, verbose_name='子菜单显示优先级'),
        ),
        migrations.AlterField(
            model_name='submenu',
            name='subMenuShow',
            field=models.BooleanField(default=False, help_text='子菜单是否显示，默认添加不显示', verbose_name='是否显示'),
        ),
        migrations.AlterField(
            model_name='submenu',
            name='subMenuUrl',
            field=models.CharField(blank=True, default='javascript:void(0)', help_text='设置子菜单Url跳转地址', max_length=50, null=True, verbose_name='子菜单Url地址'),
        ),
    ]
