# Generated by Django 3.1.6 on 2021-02-13 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FundInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fundCode', models.IntegerField(blank=True, error_messages={'invalid': '格式错误', 'null': '不能为空'}, max_length=10, null=True, verbose_name='基金代码')),
                ('fundName', models.CharField(max_length=50, verbose_name='基金名字')),
                ('isMonitor', models.BooleanField(default=True, verbose_name='是否监控')),
            ],
            options={
                'verbose_name': '基金信息',
                'verbose_name_plural': '基金信息',
                'db_table': 'apiapps_fund_info',
            },
        ),
    ]
