# Generated by Django 3.1.6 on 2021-02-13 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundinfo',
            name='fundCode',
            field=models.CharField(blank=True, error_messages={'invalid': '格式错误', 'null': '不能为空'}, max_length=10, null=True, verbose_name='基金代码'),
        ),
    ]
