# Generated by Django 3.1.6 on 2021-02-13 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiapps', '0002_auto_20210213_1717'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fundinfo',
            options={},
        ),
        migrations.AlterModelTable(
            name='fundinfo',
            table=None,
        ),
    ]
