# Generated by Django 3.1.6 on 2021-02-13 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiapps', '0003_auto_20210213_1748'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fundinfo',
            options={'verbose_name': '基金信息', 'verbose_name_plural': '基金信息'},
        ),
        migrations.AlterModelTable(
            name='fundinfo',
            table='apiapps_fund_info',
        ),
    ]
